{
 "title": "Geth Overview",
 "description": "Geth metrics overview dashboard.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(chain_head_block{client_name=\"$client_name\"}, service)"
    }
   },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   },
   { "name": "rate", "query": "1m, 2m, 5m" },
   { "name": "client_name", "label": "Client", "query": "geth" }
  ]
 },
 "panels": [
  { "title": "Builder", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bundle Simulations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(miner_bundle_simulate_success_count{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(miner_bundle_simulate_failed_count{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "fail"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rate(miner_block_build_count{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "build"
    },
    {
     "expr": "rate(miner_block_merge_count{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "merge"
    }
   ]
  },
  {
   "title": "Profit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(miner_block_profit_gauge{client_name=~\"$client_name\", service=~\"$instance\"}[$rate]) / 1000000000",
     "legendFormat": "build"
    }
   ]
  },
  { "title": "Simulation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "eth_callBundle calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(rpc_duration_eth_callBundle_success_count{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(rpc_duration_eth_callBundle_failure_count{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Durations of successful eth_callBundle calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rpc_duration_eth_callBundle_success{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"} / 1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Durations of failed eth_callBundle calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "expr": "rpc_duration_eth_callBundle_failure{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"} / 1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Validation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "flashbots_validateBuilderSubmissionV2 calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(rpc_duration_flashbots_validateBuilderSubmissionV2_success_count{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(rpc_duration_flashbots_validateBuilderSubmissionV2_failure_count{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Durations of successful eth_callBundle calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "rpc_duration_flashbots_validateBuilderSubmissionV2_success{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"}/1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Durations of failed flashbots_validateBuilderSubmissionV2 calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "rpc_duration_flashbots_validateBuilderSubmissionV2_success{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"} / 1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_sysload{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "system_cpu_syswait{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "system_cpu_procload{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "geth"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(system_memory_allocs{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "alloc"
    },
    {
     "expr": "system_memory_used{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "system_memory_held{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "held"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(system_disk_writebytes{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(p2p_ingress{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "ingress"
    },
    {
     "expr": "rate(p2p_egress{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "egress"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "p2p_peers{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "peers"
    },
    {
     "expr": "rate(p2p_dials{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "dials"
    },
    {
     "expr": "rate(p2p_serves{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "serves"
    }
   ]
  },
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(chain_head_header{client_name=~\"$client_name\", service=~\"$instance\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "chain_head_header{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "header"
    },
    {
     "expr": "chain_head_receipt{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "receipt"
    },
    {
     "expr": "chain_head_block{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "block"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_pending{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "txpool_pending{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "executable"
    },
    {
     "expr": "txpool_queued{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "gapped"
    },
    {
     "expr": "txpool_local{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(chain_head_receipt{client_name=~\"$client_name\", service=~\"$instance\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_queued{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(chain_head_block{client_name=~\"$client_name\", service=~\"$instance\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_local{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "chain_execution{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "execution (q=$quantile)"
    },
    {
     "expr": "chain_validation{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "validation (q=$quantile)"
    },
    {
     "expr": "chain_write{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "commit (q=$quantile)"
    },
    {
     "expr": "chain_account_reads{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "account read (q=$quantile)"
    },
    {
     "expr": "chain_account_updates{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "account update (q=$quantile)"
    },
    {
     "expr": "chain_account_hashes{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "account hashe (q=$quantile)"
    },
    {
     "expr": "chain_account_commits{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "account commit (q=$quantile)"
    },
    {
     "expr": "chain_storage_reads{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "storage read (q=$quantile)"
    },
    {
     "expr": "chain_storage_updates{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "storage update (q=$quantile)"
    },
    {
     "expr": "chain_storage_hashes{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "storage hashe (q=$quantile)"
    },
    {
     "expr": "chain_storage_commits{quantile=\"$quantile\", client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "storage commit (q=$quantile)"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(txpool_valid{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "valid"
    },
    {
     "expr": "rate(txpool_invalid{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "invalid"
    },
    {
     "expr": "rate(txpool_underpriced{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_disk_read{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "rate(eth_db_chaindata_disk_write{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_read{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "ancient read"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_write{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 64 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_read{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "eth_db_chaindata_disk_write{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "eth_db_chaindata_ancient_read{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "ancient read"
    },
    {
     "expr": "eth_db_chaindata_ancient_write{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 64 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_size{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "leveldb"
    },
    {
     "expr": "eth_db_chaindata_ancient_size{client_name=~\"$client_name\", service=~\"$instance\"}",
     "legendFormat": "ancient"
    }
   ]
  },
  {
   "title": "Trie Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clean cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(trie_memcache_clean_read{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "hit"
    },
    {
     "expr": "rate(trie_memcache_clean_write{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Dirty cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(trie_memcache_gc_size{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(trie_memcache_flush_size{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "overflow"
    },
    {
     "expr": "rate(trie_memcache_commit_size{client_name=~\"$client_name\", service=~\"$instance\"}[$rate])",
     "legendFormat": "commit"
    }
   ]
  }
 ]
}